--!A generic AI agent harness framework based on xmake lua
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Copyright (C) 2015-present, Xmake Open Source Community.
--
-- @author      ruki
-- @file        compact.lua
--

--
-- the context compaction
--
-- when the conversation approaches the context window of the model, the old
-- events are replaced with a summary generated by the small model, so a long
-- session never dies with a context overflow.
--

-- imports
import("harness.llm.llm")
import("harness.util.tokens")
import("harness.config.config")

-- the prompt which generates the summary
local SUMMARY_PROMPT = [[Summarize this conversation so that another agent can continue the work
without reading the history. Be complete but dense, and write it as the notes, not as a report.

Cover:
1. What the user asked for, including the exact wording of the constraints.
2. What has been done so far: the files created or changed, the commands run and their results.
3. The current state: what works, what is broken, what was just being worked on.
4. What is left to do next.
5. The important technical facts discovered: the paths, the apis, the error messages.

Do not invent anything which is not in the history.]]

-- should the context be compacted?
--
-- @return  true, the used ratio
--
function should(harness, session)
    local settings = harness:config().context or {}
    if settings.autocompact == false then
        return false, 0
    end
    local provider = config.provider(harness:config())
    local contextsize = provider.contextsize or 131072
    local used = session:contexttokens()
    local ratio = used / contextsize
    return ratio >= (settings.threshold or 0.82), ratio
end

-- get the used context ratio
function ratio(harness, session)
    local provider = config.provider(harness:config())
    local contextsize = provider.contextsize or 131072
    return session:contexttokens() / contextsize, contextsize
end

-- compact the session
--
-- @param opt   the options, e.g. {keeprecent = 6, manual = true, focus = ".."}
-- @return      the summary text, or nil and the errors
--
function run(harness, session, opt)
    opt = opt or {}
    local settings = harness:config().context or {}
    local keeprecent = opt.keeprecent or settings.keeprecent or 6
    local messages = session:messages()
    if #messages <= keeprecent + 2 then
        return nil, "the conversation is too short to compact."
    end

    -- build the history text for the summarizer
    local history = {}
    for idx = 1, math.max(1, #messages - keeprecent) do
        local message = messages[idx]
        local role = message.role
        local content = message.content or ""
        if role == "tool" then
            content = string.format("[tool %s] %s", message.toolname or "", content)
            if #content > 2000 then
                content = content:sub(1, 2000) .. " ..[truncated]"
            end
        elseif message.toolcalls then
            local names = {}
            for _, toolcall in ipairs(message.toolcalls) do
                table.insert(names, toolcall.name)
            end
            content = content .. string.format(" [called: %s]", table.concat(names, ", "))
        end
        table.insert(history, string.format("%s: %s", role, content))
    end

    local prompt = SUMMARY_PROMPT
    if opt.focus and opt.focus ~= "" then
        prompt = prompt .. string.format("\n\nThe user asks you to focus on: %s", opt.focus)
    end

    local provider = config.provider(harness:config())
    local result = llm.complete(provider, {
        model = provider.models.small or provider.models.main,
        system = prompt,
        messages = {{role = "user", content = table.concat(history, "\n\n")}},
        stream = false,
        maxtokens = 4096,
        temperature = 0.2
    }, {ontick = opt.ontick})
    if result.errors then
        return nil, result.errors
    end
    if result.usage then
        session:usage_update(result.usage)
    end

    local summary = string.format("# The summary of the previous conversation\n\n%s", result.content)
    local dropped = session:compact(summary, keeprecent)
    return summary, nil, dropped
end
